node:
  node_id: 21
  instance_id: http2client-2
  name: http2client-2
  type: http2_client
  group: tool-client
  ip: 127.0.0.1

target: http://127.0.0.1:8080
message_id: 1001
session_id: cli2
unique_session: true
body: hello
timeout: 10s
concurrency: 4
qps: 20
duration: 30s
n: 0
master_url: http://127.0.0.1:9200

resource:
  cpu_cores: 1
  memory: 512M
