udp:
  listen: 0.0.0.0
  port: 9100

gateway:
  host: http2gw
  port: 9000

node:
  node_id: 2
  instance_id: logic-docker
  ip: logic

services:
  - service_id: 100
    service_name: call
    message_types: [1001, 1002, 1003]

heartbeat:
  interval: 1000ms
  timeout: 3000ms
